Loading pytorch-gpu/py3/1.6.0
  Loading requirement: gcc/8.3.1 cuda/10.2 nccl/2.6.4-1-cuda
    cudnn/7.6.5.32-cuda-10.2 intel-mkl/2020.1 magma/2.5.3-cuda
    openmpi/4.0.2-cuda
++ sed -n 14p parameters_combinations/mnist_classifier_ratio.txt
+ LINE='--gpu_devices 0 --max_iter 100 --batch_size 250 --use_scheduler True --lr 1e-3 --GMP True  --z_struct_size 20 --is_encoder_struct True --big_kernel_size 8 --two_conv_layer True --three_conv_layer True --kernel_size_1 4 --kernel_size_2 4 --kernel_size_3 4 --BK_in_first_layer True --BK_in_second_layer False --BK_in_third_layer False --stride_size 1 --hidden_filters_layer1 128 --hidden_filters_layer2 128 --hidden_filters_layer3 128 --lambda_class 1 --ratio_reg False --lambda_ratio_reg 1 --loss_min_distance_cl False --lambda_var_distance 1 --loss_distance_mean False --lambda_distance_mean 1 --Hmg_dst_loss False --lambda_hmg_dst 1 --uniq_code_dst_loss True --lambda_uniq_code_dst 0.1 --dataset_balanced True --binary_z True --binary_first_conv False --binary_second_conv False --binary_third_conv True --exp_name mnist_struct_baseline_scheduler_binary_1_8_uniq_code_target_2'
+ echo --gpu_devices 0 --max_iter 100 --batch_size 250 --use_scheduler True --lr 1e-3 --GMP True --z_struct_size 20 --is_encoder_struct True --big_kernel_size 8 --two_conv_layer True --three_conv_layer True --kernel_size_1 4 --kernel_size_2 4 --kernel_size_3 4 --BK_in_first_layer True --BK_in_second_layer False --BK_in_third_layer False --stride_size 1 --hidden_filters_layer1 128 --hidden_filters_layer2 128 --hidden_filters_layer3 128 --lambda_class 1 --ratio_reg False --lambda_ratio_reg 1 --loss_min_distance_cl False --lambda_var_distance 1 --loss_distance_mean False --lambda_distance_mean 1 --Hmg_dst_loss False --lambda_hmg_dst 1 --uniq_code_dst_loss True --lambda_uniq_code_dst 0.1 --dataset_balanced True --binary_z True --binary_first_conv False --binary_second_conv False --binary_third_conv True --exp_name mnist_struct_baseline_scheduler_binary_1_8_uniq_code_target_2
+ python3 -u main.py --gpu_devices 0 --max_iter 100 --batch_size 250 --use_scheduler True --lr 1e-3 --GMP True --z_struct_size 20 --is_encoder_struct True --big_kernel_size 8 --two_conv_layer True --three_conv_layer True --kernel_size_1 4 --kernel_size_2 4 --kernel_size_3 4 --BK_in_first_layer True --BK_in_second_layer False --BK_in_third_layer False --stride_size 1 --hidden_filters_layer1 128 --hidden_filters_layer2 128 --hidden_filters_layer3 128 --lambda_class 1 --ratio_reg False --lambda_ratio_reg 1 --loss_min_distance_cl False --lambda_var_distance 1 --loss_distance_mean False --lambda_distance_mean 1 --Hmg_dst_loss False --lambda_hmg_dst 1 --uniq_code_dst_loss True --lambda_uniq_code_dst 0.1 --dataset_balanced True --binary_z True --binary_first_conv False --binary_second_conv False --binary_third_conv True --exp_name mnist_struct_baseline_scheduler_binary_1_8_uniq_code_target_2
--- Logging error ---
Traceback (most recent call last):
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
KeyError: 'asc_time'
Call stack:
  File "main.py", line 309, in <module>
    main(args)
  File "main.py", line 31, in main
    net = SolverClassifier(arguments)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 356, in __init__
    self.test_loader_size))
Message: 'Dataset mnist: train with 60000 samples and 10000 test samples'
Arguments: ()
Traceback (most recent call last):
  File "main.py", line 309, in <module>
    main(args)
  File "main.py", line 31, in main
    net = SolverClassifier(arguments)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 485, in __init__
    self.net, self.device = gpu_config(net)
  File "/gpfsdswork/projects/rech/rjg/uiu23ko/Thesis/Pytorch_vanilla_Beta_VAE/solver.py", line 174, in gpu_config
    model.to(device)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 607, in to
    return self._apply(convert)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.6.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 605, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
+ wait
+ echo 'All done !'
