--- Logging error ---
Traceback (most recent call last):
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
KeyError: 'asc_time'
Call stack:
  File "main.py", line 244, in <module>
    main(args)
  File "main.py", line 30, in main
    net = SolverClassifier(arguments)
  File "/data1/data/expes/julien.dejasmin/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 294, in __init__
    self.test_loader_size))
Message: 'Train mnist with 60000 train samples, 6000 valid samples and 10000 test samples'
Arguments: ()
  0%|          | 0/50.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 244, in <module>
    main(args)
  File "main.py", line 33, in main
    net.train()
  File "/data1/data/expes/julien.dejasmin/Thesis/Pytorch_vanilla_Beta_VAE/solver_classifier.py", line 551, in train
    Classification_loss = F.nll_loss(prediction, labels)
  File "/data1/home/julien.dejasmin/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'target' in call to _thnn_nll_loss_forward
  2%|‚ñè         | 1/50.0 [00:01<00:55,  1.13s/it]
